LANGUAGE_MAP = {
    'amh': 'Amharic',
    'arb': 'Arabic',
    'ben': 'Bengali',
    'deu': 'German',
    'eng': 'English',
    'fas': 'Persian',
    'hau': 'Hausa',
    'hin': 'Hindi',
    'ita': 'Italian',
    'khm': 'Khmer',
    'mya': 'Burmese',
    'nep': 'Nepali',
    'ori': 'Odia',
    'pan': 'Punjabi',
    'pol': 'Polish',
    'rus': 'Russian',
    'spa': 'Spanish',
    'swa': 'Swahili',
    'tel': 'Telugu',
    'tur': 'Turkish',
    'urd': 'Urdu',
    'zho': 'Chinese'
}